### PR TITLE
AM-3773: SAML RelayState support

### PR DESCRIPTION
**Pull request by marcantoine-bibeau**
#### JIRA story
https://appdirect.jira.com/browse/AM-3773

#### Description
SAML RelayState is not used if present

#### Notification(s)
@yanavery @ersutter

### CODE REVIEW

**Comment by yanavery** [comment]
LGTM. @rajanvyas84, ready for QA validation.

**Comment by camloken** [comment]
Hey Yan, I noticed I'm still getting notifications from AppDirect repo for some strange reason. I thought I should mention this. I'm at a new company now (BrightSquid). Someone there should probably remove me from the repo. 

git user: Cameron Loken
git email: camloken@gmail.com

Thanks,
Cameron

**Comment by totof3110** [comment]
@camloken : this is a public repo. If you don't want to receive notifications you can simply "unwatch" it.

**Comment by camloken** [comment]
Ok thanks, I did not realize AppDirect had public repos.

**Comment by enriquedacostacambio** [comment]
validated

**Pull request merged**
