### PR TITLE
AM-5011-meta-script-to-skip-googlebot

### PR DESCRIPTION
**Pull request by rezafarhadi**
JIRA: 
https://appdirect.jira.com/browse/AM-5011

sample-isv.cfapps.io Discoverable by Googlebot

@perry-wong @yanavery

### CODE REVIEW

**Comment by yanavery** [comment]
@perry-wong does it LGTY?

**Comment by rezafarhadi** [comment]
@yanavery @perry-wong 
I deployed on my local machine and the page loads successfully.. is it fine as validation? not sure how to validate the html header meta and script
screen shot 2017-01-19 at 2 20 17 pm

**Comment by rezafarhadi** [comment]
another screenshot from the html source which shows meta and script added
screen shot 2017-01-19 at 2 24 25 pm

**Comment by yanavery** [comment]
Thanks @rezafarhadi and @perry-wong. Merging.

**Pull request merged**
